### 00.PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: github discussion

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors



In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() # Python int

7

In [ ]:
# VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [ ]:
# MATRIX
MATRIX = torch.tensor([[3, 4],
                       [4, 5]])
MATRIX

tensor([[3, 4],
        [4, 5]])

In [ ]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [ ]:
MATRIX[0]

tensor([3, 4])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[3, 4, 4],
                        [4, 5, 6],
                        [1, 2, 3]]])
TENSOR

tensor([[[3, 4, 4],
         [4, 5, 6],
         [1, 2, 3]]])

In [ ]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

### Random tensors

Why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> Update random numbers -> Look at data -> Update numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8350, 0.4740, 0.3387, 0.0568],
        [0.7972, 0.7054, 0.8104, 0.8611],
        [0.2367, 0.1887, 0.9185, 0.5464]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h, w, c
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_t = torch.rand(3, 4)
random_t * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
### Random tensors
ones = torch.ones(size=(3, 4))
ones.dtype, ones

(torch.float32,
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### Range of tensors and tensors-like

In [ ]:
# torch.arange()
one_to_9 = torch.arange(0, 10, step = 2)
one_to_9

tensor([0, 2, 4, 6, 8])

In [ ]:
# tensor-like
ten_zeros = torch.zeros_like(one_to_9)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# float 32 tensor
float_32_t = torch.tensor([3.0, 4, 5],
                          dtype=None, # what datatype is the tensor
                          device=None, # default cpu: cpu or cuda
                          requires_grad=False) # require pytorch to track gradient of the tensor
float_32_t

tensor([3., 4., 5.])

In [ ]:
float_32_t.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_t.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([2, 3, 4], dtype=torch.long)
int_32_tensor

tensor([2, 3, 4])

In [ ]:
float_32_t * int_32_tensor

tensor([ 6., 12., 20.])

### Getting information about tensor (attributes)

1. tensor.dtype
2. tensor.shape
3. tensor.device

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor.dtype, some_tensor.shape, some_tensor.device, some_tensor.size()

(torch.float32, torch.Size([3, 4]), device(type='cpu'), torch.Size([3, 4]))

### Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10, tensor - 10

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [ ]:
# Try out PyTorch in-build function
torch.add(tensor, 10), torch.mul(tensor, 10), torch.sub(tensor, 10)

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

### Matrix Multiplication

1. Element-wise
2. Matrix multiplication (dot product)

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* (x, 2) @ (2, y)

2. The resulting matrix has the shape of **outer dimensions**:
*  (x, 2) @ (2, y) -> (x, y)

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.1681, 0.5094, 0.5560, 0.4145],
        [0.1122, 0.2892, 0.3106, 0.2315],
        [0.6093, 0.7503, 0.7096, 0.5272]])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.31 ms, sys: 888 µs, total: 2.2 ms
Wall time: 7.7 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 122 µs, sys: 9 µs, total: 131 µs
Wall time: 137 µs


tensor(14)

### One of the most common errors in deep learning is: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a give tensor.

In [ ]:
tensor_B.T, t

### Find the min, max, mean, sum (tensor aggregation)

In [2]:
import torch

In [3]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [5]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [7]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [8]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [14]:
x.argmin().item(), x.argmax(), torch.argmin(x), torch.argmax(x)

(int, tensor(9), tensor(0), tensor(9))

### **Reshaping, stacking, squeezing and unsqueezing tensors**

* Reshaping - reshape an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes **all** `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [37]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
# Add an extra dimension
x_reshaped = x.reshape((1, -1))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [26]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [29]:
torch.vstack([x]*4)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
x_reshaped = x_reshaped.reshape(1, 9, 1)
x_reshaped

tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [41]:
x_reshaped = x_reshaped.squeeze()
x_reshaped

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
x_reshaped.unsqueeze(0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [43]:
x_ori = torch.rand(224, 224, 3)

In [ ]:
x_permuted = x_ori.permute(2, 0, 1)

In [47]:
x = torch.tensor([[1, 2, 3], [3, 4, 5]])
x_permuted = x.permute(1, 0)
x_permuted, x

(tensor([[1, 3],
         [2, 4],
         [3, 5]]),
 tensor([[1, 2, 3],
         [3, 4, 5]]))

In [48]:
x[0, 0] = 100
x_permuted

tensor([[100,   3],
        [  2,   4],
        [  3,   5]])

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [49]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [50]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0, 0]

tensor([7, 8, 9])

In [52]:
x[:, 0]

tensor([[1, 2, 3]])

In [53]:
 x[:, :, 1]

tensor([[2, 5, 8]])

In [54]:
  x[:, 1, 1]

tensor([5])

In [55]:
x[:, 2, 2]

tensor([9])

In [56]:
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [58]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [60]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [61]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [64]:
import random
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

!: run this on the command line

GPU and PyTorch:
* Get PyTorch to store data (tensors) and compute on data (tensors) -> Use **torch.cuda** package. PyTorch store model and tensor on GPU if available
* Set up the code so it ran on CPU or the GPU if it was available.
* PyTorch has features to let you run a process across all GPUs.
* If tensor is on GPU, can't transform it to NumPy

In [65]:
torch.cuda.is_available()

False

In [66]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
torch.cuda.device_count()

cpu


0

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor.device)
tensor_device = tensor.to(device)

# Exercises

In [1]:
import torch

In [2]:
tensor = torch.rand(7, 7)
tensor

tensor([[0.2363, 0.0986, 0.9381, 0.9746, 0.9196, 0.6857, 0.5383],
        [0.1649, 0.0654, 0.3867, 0.9175, 0.1646, 0.0131, 0.2886],
        [0.0109, 0.8427, 0.9363, 0.2954, 0.1400, 0.3319, 0.2860],
        [0.6398, 0.6068, 0.3322, 0.1450, 0.9271, 0.9362, 0.4636],
        [0.9260, 0.0334, 0.4398, 0.9588, 0.4976, 0.6023, 0.1456],
        [0.8842, 0.7426, 0.3942, 0.2516, 0.7181, 0.6655, 0.8308],
        [0.8441, 0.9664, 0.4673, 0.2284, 0.9942, 0.5910, 0.7103]])

In [3]:
tensor2 = torch.rand(1, 7)
torch.matmul(tensor, tensor2.T)

tensor([[1.5080],
        [0.7489],
        [0.9938],
        [1.2498],
        [1.2761],
        [1.2087],
        [1.2685]])

In [18]:
torch.cuda.manual_seed(0)

In [20]:
torch.manual_seed(12)
torch.initial_seed()

12

In [21]:
torch.cuda.initial_seed()

12

In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(1234)
tA = torch.rand(2, 3).to(device)

torch.manual_seed(1234)
tB = torch.rand(2, 3).to(device)

res = tA @ tB.T
res

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [12]:
torch.min(res), torch.max(res)

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [13]:
res.argmin(), res.argmax()

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

In [14]:
tC = torch.rand(1, 1, 1, 10)
# [[[[x, x, x, x, x,x x,...]]]]

tC

tensor([[[[0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208,
           0.2793, 0.6817]]]])

In [15]:
tC.squeeze()

tensor([0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208, 0.2793,
        0.6817])